# Generated by Django 5.0.1 on 2024-01-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fridge',
        ),
        migrations.CreateModel(
            name='FridgeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fridge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='products',
            field=models.ManyToManyField(related_name='fridges', through='main.FridgeProduct', to='main.product'),
        ),
    ]
