# Generated by Django 5.0.1 on 2024-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
